### ISSUE TITLE
Broken plugin python file does not report error

### ISSUE THREAD

**Issue by velocirobbie** [djgroen/FabSim3#101]
If my plugin file 'FabMD.py' has a syntax error or similar, typing

`fab localhost lamms`

returns: 

`Warning: Command(s) not found:
    lammps

Available commands:

    archer                             partial(func, *args, **keywords) - new fun...
    archive  ......`

It would be better if it said there was an error.

I assume somewhere fabric is catching this exception

**Comment by djgroen** [comment]
In general there are a few issues with the way Fabric captures exceptions in tasks. In addition, the list of commands shown is also not quite consistent with the structure of the plugins. We should investigate this in detail, ideally before M12.

**Comment by djgroen** [comment]
Okay, I found a solution for this, but it's a little tricky:

Basically, we need to override main.py in Fabric, and then modify the way that Fabric outputs diagnostics.

I now made a change on this, and I'll file a pull request for it.

**Comment by djgroen** [comment]
After discussion with @dww100 I think it makes sense to rename this overridden version from `fab` to `fabsim`. It will be functionally the same as `fab`, but the way it conveys info will hopefully be better.

I'm not sure yet if this should be in the M12 release, but we did have a lot of complaints about aspects surrounding this... any opinions?

**Comment by djgroen** [comment]
This issue is now solved. Question is whether we want to update our tutorials to use `fabsim` instead of the `fab` command...
