### ISSUE TITLE
Can't use FabSim to connect on remote throught an ssh tunnel

### ISSUE THREAD

**Issue by NicolasMonnier** [djgroen/FabSim3#102]
The network at work is really (really) limited, so a direct ssh connection to a server using the port 22 is not allowed. 

for example I can't directly connect to Eagle. To do it I have to first connect to one of our machine which is able to connect to outside world (port 22) then I can connect to Eagle machine. 

The problem is I can't use this method using FabSim3 to connect on Eagle because the `run(cmd)` command  will connect to the remote using `user@remote` which is a direct connection to the remote. 

Do you know any way to use ssh tunnel instead of direct connection with fabric (or FabSim3) ?

I haven't had a look yet but I think It's an interesting question !

**Comment by djgroen** [comment]
Hi Nicholas,

I believe this is a feature we could add, and that may benefit others as well.

Could you give me the one- or two-liner command that you use to run a command remotely using SSH tunnelling?

We could choose to add this by M15.

**Comment by NicolasMonnier** [comment]
The following commands are to connect to the remote machine using ssh tunnel 

`ssh -t name1@host1:port1 ssh name2@host2:port2` 

Newer version of ssh is simpler : 
`ssh -J name1@host1:port1 name2@host2:port2`

Second option is to modify your ~.ssh/config :  

```
Host host1
        HostName host1.fr
        User name1

Host host2
        HostName host2.fr
        User name2
        ProxyCommand ssh host1 -W %h:%p
```
And use `ssh host2`

note that this syntax is only for ssh version < 7.3.
For newer version, they replaced `ProxyCommand ssh host1 -W %h:%p` by `ProxyJump host1`


Haven't look yet if there is other alternative than these one!

**Comment by djgroen** [comment]
Nicolas now left BULL, so clearly this was not a priority...
