### ISSUE TITLE
Migration tutorial testing

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#103]
Hi guys,

I composed an early version of the Migration tutorial now, and I think it may be at the point where we can try some first testing.

@orbitfold would you perhaps be willing to give this a first test? I am sure you'll hit issues, so feel free to leave them here. Also any advice for explanations / clarifications etc. will be very useful! :)

**Comment by djgroen** [comment]
One more note here: please don't try the "going the extra mile" section yet. That still needs some more work :).

(However, you can try to run Flee on eagle if you like. We know that that should be working).

**Comment by djgroen** [comment]
Okay, this tutorial is in near-final state now. @orbitfold would you be able to establish testing around it?

**Comment by arabnejad** [comment]
_section 3. Going the extra mile_ is updated,
I tested FabFlee tutorial again :) everything works fine 
I think we can close this issue if you agree @djgroen

**Comment by djgroen** [comment]
Done!
