### ISSUE TITLE
Fab archer monitor broken

### ISSUE THREAD

**Issue by velocirobbie** [djgroen/FabSim3#104]
Can't check queue status on archer. I don't understand how this function is supposed to work sorry.

fab archer monitor

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/robertsinclair/codes/FabSim3/base/manage_remote_job.py", line 339, in monitor
    execute(stat)
NameError: name 'stat' is not defined`

**Comment by djgroen** [comment]
I looked into this, and it appears that this functionality got changed in some of Hamid's commits.

Among other things, `stat' got changed to `job_stat'.

Robbie, could you check if fab archer job_stat works for you? If so, then we can refactor this in a straightforward way.

I'll tag Hamid on this as well.

**Comment by velocirobbie** [comment]
Doesn't seem to work for me because my jobs are not getting put into a '$local_jobsDB_path'. I have never heard of this before, do I need to set it up?

**Comment by djgroen** [comment]
No, this to me looks like a refactor that went wrong. Hamid probably completely overlooked that people use these commands also when operating supercomputers directly.

I will reinstate the original stat command for now, but we will need to find a single command that does it for both QCG and SSH-driven jobs.

**Comment by djgroen** [comment]
I pushed a fix now, and `fab archer stat' and `fab archer monitor' work for me now. For you too?

**Comment by velocirobbie** [comment]
Yep both work for me, could you add it to master?

**Comment by djgroen** [comment]
Yes. I think I'll merge the branch in altogether. Checking it now :)

**Comment by djgroen** [comment]
@velocirobbie Merged it in now. Any luck? :)

**Comment by velocirobbie** [comment]
Still works, leave this open for the issue above

**Comment by djgroen** [comment]
`stat` and `job_stat` now do the same thing. So unless I broke anything I think this issue should be solved.

**Comment by djgroen** [comment]
in master now, so will close this.
