### ISSUE TITLE
Where to put custom workflow functions

### ISSUE THREAD

**Issue by velocirobbie** [djgroen/FabSim3#106]
I've implemented the fabmd easyvvuq example. Now lets say I'm an alpha user and I want a similar function with some changes specific to my own workflow, it would be nice to put this in a separate file that is imported by FabMD.py that is not tracked by git so that it doesn't clutter the repo or get overwritten. Any suggestions on how to do this?

**Comment by djgroen** [comment]
There are many ways to do this, but the key thing is that we need to wire up such files such that they get imported in fabfile.py. Technically this is doable, and I can think of two ways:

1. We add a `fab*_user.py`, which is a single file with user-specific functionality in each Plugin folder.
2. We add an env variable that allows users to add their custom file paths for FabSim tasks.

(1) is simpler, has a nice convention to it, but is very inflexible.
(2) is very flexible, but could create a mess if people start adding too many files, and functions begin to clash.

Opinions?

**Comment by djgroen** [comment]
@velocirobbie Actually, Diana has found an elegant way to import custom functions in FabSim. 

At the bottom of FabFlee.py she added:
from plugins.FabFlee.run_simulation_sets import *

(https://github.com/djgroen/FabFlee/blob/master/FabFlee.py)

That seems to work for all practical purposes, so you can use the same approach :).

That being said, I think it's worthwhile to close this issue now.
