### ISSUE TITLE
Results being overwritten

### ISSUE THREAD

**Issue by velocirobbie** [djgroen/FabSim3#107]
If I submit a fabsim job from a config_dir that has been used before there is a chance some stuff will get overwritten in the direcories:
remote_machine:/FabSim3/config_files/
remote_machine:/FabSim3/results/
local_machine:/FabSim3/results/ 
Could we discuss what we want the desired behaviour to be?

1. Continue as is, with no warnings
2. Check in the directories listed above, and halt the execution and ask if you want to continue (e.g. a job with this name has been run before, some of its results might get overwritten, would you like to continue y/n?)
3. If there is a clash add a unique identifier to the job name so there is no clash. We could use the date/time or a hash.
4. Always give jobs a unique identifier (this could make finding the job results less intuitive)

**Comment by djgroen** [comment]
Ideally these two:

`remote_machine:/FabSim3/results/
local_machine:/FabSim3/results/`

should be in different directories, otherwise you might get strange overwrites when running on localhost. We could check for that in the env whenever a job is submitted, and give off a warning.

As for your main question, I think it's good to default to option 2, but to allow for a setting in machines_user.yml or elsewhere to override it and enable option 1.

**Comment by velocirobbie** [comment]
Things I've been running the directory in the two you have mentioned is always the same, why would it be different when you fetch down the results?

**Comment by djgroen** [comment]
remote_machine:/FabSim3/results/ = a run directory, which contains runs performed on the target machine (which can be the local machine).
local_machine:/FabSim3/results/ = a results directory in your local FabSim3 installation. If you have the run directory defined as that same folder, then runs on localhost may inadvertently overwrite previously fetched results.

Should we perhaps build in a safety check to verify that the rundir and the install dir on localhost are indeed different, and force users to follow that?

**Comment by arabnejad** [comment]
Or we can set a temporary folder, `<fabsim directory>/tmp` in yml files, or set it as default in fabsim env parameters , so all temporary files will be saved there, and be fetch command, those files will be retrieved into `<fabsim directory>/results`

**Comment by arabnejad** [comment]
@djgroen with the new automated FabSim3 installation functionality, by default
the localhost execution will be saved  `<FabSim3 folder>/localhost_exe` folder

**Comment by djgroen** [comment]
@arabnejad That is a good solution. Could you update the documentation to reflect this and then close this ticket?

**Comment by arabnejad** [comment]
we also have another check layer which prevents of executing localhost runs on the FabSim3 root folder: https://github.com/djgroen/FabSim3/commit/6ecf4cd8dcfbfbbfa3edfa6f6d8fc6072747c9c8
