### ISSUE TITLE
Plugin Install : https vs ssh 

### ISSUE THREAD

**Issue by NicolasMonnier** [djgroen/FabSim3#109]
During most plugin installation a `git clone` is used to download the corresponding plugin. 
There is usually 2 common way to do this git clone : 

`git clone git@github.com:AccountName/PluginName.git`

or

`git clone https://github.com/AccountName/PluginName.git`

The first one will download the plugin using ssh and try to connect to the host github.com though the port 22. This solution won't be affect by proxy configuration and may failed if the user's network doesn't allow the usage of this port (or usally more complicated). 
In this case the following problem will appear :           

`ssh: connect to host github.com port 22: Connection timed out`

The second one will use the https protocole wich is directly affected by an https_proxy so the github repo could be download without issue (if there is one). 
(tell me if I'm wrong, not 100% sure of this explanation but that's the general idea)

As @djgroen suggest, should we add an option in FabSim3 to allow people to pull from https by default instead of using SSH? 

This is low-priority ticket since this problem won't affect most of the user.

**Comment by arabnejad** [comment]
FabMUSCLE was the only plugin uses `git@github.com<xxxx>` address instead of  `https://github.com<xxxx>` in `FabSim3/deploy/plugins.yml` file

The repository URL is updated by https://github.com/djgroen/FabSim3/commit/25148ed4bede85d732e94ae7b709d12dcdc6159a
