### ISSUE TITLE
Unclear error message 

### ISSUE THREAD

**Issue by NicolasMonnier** [djgroen/FabSim3#110]
I got the follong problem with FabFlee plugin (It's not specific to FabFlee at all, It already happened to me before): 

`fab localhost flee:mali,simulation_preiod=300` will give me the following error : 

```
`SCRIPT:  flee
MODULE COMMANDS:  []
ORIGINAL PATTERN:

cd $job_results
$run_prefix

if [ -z "$flee_location" ]
then
echo "Please set $$flee_location in your deploy/machines_user.yml file."
else
export PYTHONPATH=$flee_location:$$PYTHONPATH
fi

/usr/bin/env > env.log

python3 run.py input_csv source_data $simulation_period simsetting.csv > out.csv

SAFELY SUBSTITUTED PATTERN:

cd /home/nicolas/FabSim3/results/mali_localhost_16
echo Running...

if [ -z "/home/nicolas/VECMA/test_install_fabsim3/flee-release" ]
then
echo "Please set $flee_location in your deploy/machines_user.yml file."
else
export PYTHONPATH=/home/nicolas/VECMA/test_install_fabsim3/flee-release:$PYTHONPATH
fi

/usr/bin/env > env.log

python3 run.py input_csv source_data $simulation_period simsetting.csv > out.csv

ERROR: FABSIM_TEMPLATE_KEYERROR
Template variables were not found in FabSim env dictionary: These variables need to be added, with a default value set.
FabSim performed a 'safe_substite' and print the original template and the partially substituted one (both are given above this message). Variables that are missing in the env dictionary will be displayed unsubstituted in the output text. FabSim will now terminate as these errors would result in unpredictable behavior otherwise.
Disconnecting from localhost... done.`
```

That's a really long error message and It took me some time before I realize it was a syntax error : I wrote `simulation_preiod` instead of `simulation_period`. 

The error message I got really didn't help to find what was wrong while the error was just a wrong input parameter.. 

Do you think it is possble to make this kind of issue more clear?

**Comment by djgroen** [comment]
@NicolasMonnier First and foremost: can you describe the error message that you would like to see in this case?


To be more detailed, this mistake would previously give a "key not found" error, which might have been useful in your case, but would also have triggered in a wide range of other (less clear) cases, and led to a lot of confusion previously.

Most often, people forget to include parameters on the command line, and I think in those cases this error message is reasonably clear.

However, we may want to add separate mechanisms that prevent or report errors, e.g. by adding verification routines to command line arguments, or by making command-line parameters shorter (to reduce the chance of typos).

**Comment by NicolasMonnier** [comment]
@djgroen I was thinking about `Error : <simulation_preiod> is an unknonw parameter ` if a wrong parameter is set  or  `Error Missing Parameter : simulation_period` for parameters that must be declared (additionaly to the current error message!).

To be honest the first time I had the error message I wrote in my previous post (I don't remember why) I was really confuse and didn't really know what was wrong. The thing is, at the beginning,  I didn't see the difference between the `SAFELY SUBSTITUTED PATTERN` and the Pattern I should have. The reason was the missing variables had the same typo as the text. 
So another idea would be to hilight or change the typo of the missing variables in the `SAFELY SUBSTITUTED PATTERN`

Anyway, I think it's an open question because the problems I got was probably just "beginner" error. I think the best solution to avoid this kind of errors is a strong documentation to list the potential parameters of command-lines (which is the case now so all fine!). Other solutions are just an extra to help the beginner. 

Any thought about it ?

**Comment by djgroen** [comment]
Yes, I think the simplest way to solve this is to make simulation_period a required argument. Without it we do not know what to run anyway. I now added this to fabflee, and when I type your command, it now returns:
```
derek@vecma01:~/Codes/FabSim3/plugins/FabFlee$ fab localhost flee:mali,simulation_preiod=300
MODULE COMMANDS:  []
{'all': [], 'dummy': []}
MODULE COMMANDS:  []
[derek@localhost] Executing task 'flee'
Traceback (most recent call last):
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
TypeError: flee() missing 1 required positional argument: 'simulation_period'
```

Looks better, right?

**Comment by NicolasMonnier** [comment]
Yes looks better to me :+1:

**Comment by djgroen** [comment]
Okay, I'll merge and close this then.
