### ISSUE TITLE
Review: Any comments for the FabSim3 web page?

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#114]
It's here: https://fabsim3.readthedocs.io/en/latest/

**Comment by NicolasMonnier** [comment]
`FabSim3 is publicly available at: http://www.github.com/djgroen/FabSim`

When you click on the link, you go to `https://github.com/UCL-CCS/FabSim`

So I guess you forgot a 3 in the first one? Or do you plan to merge the 2 repo ?

**Comment by djgroen** [comment]
@NicolasMonnier I forgot to type the "3" indeed, but the automatic redirect is a little annoying.

Anyway, I guess this is done as well then. If people find issues, they can always raise new issues :).
