### ISSUE TITLE
MAC platform instructions unclear

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#120]
See this feedback: 

"Updating Fabsim using git pull gave no issues. Running FabDummy gave following error : Fatal error: Low level socket error connecting to host localhost on port 22: Unable to connect to port 22 on 127.0.0.1 or ::1 This was corrected by enabling remote login. When running dummy_test, it won’t accept my private key passphrase (blank space as I use password-less ssh).Made a new key with a passphrase, this got the past the first problem. Then it asked me for my password (unclear whether it wanted the machine password or the ssh password), but nothing worked. In machines_user.yml, I typed in my localhost username in the default section, but it turned out this was the wrong thing to do. So I changed it to “User” and then tried dummy_test again, and it worked. 

Note - I am a Mac user. Trying to run dummy_ensemble gave me this error: Fatal error: run() received nonzero return code 1 while executing! Requested: mkdir -p /home/User/FabSim3/config_files; mkdir -p /home/User/FabSim3/results; mkdir -p /home/User/FabSim3/scripts; mkdir -p /home/User/FabSim3/config_files/dummy_test Executed: /bin/bash -l -c "mkdir -p /home/User/FabSim3/config_files; mkdir -p /home/User/FabSim3/results; mkdir -p /home/User/FabSim3/scripts; mkdir -p /home/User/FabSim3/config_files/dummy_test"

**Comment by djgroen** [comment]
I clarified the installation instructions for Mac users, but putting it in a blockquote, and adding a bold header.

Note that the original instructions had a big heading for Mac users in the dependencies field (which was picked up by this user), but no heading at all in step 3 of the installation (which was overlooked by this user). The new formatting is more consistent, and hopefully still clear to Mac users without being screamy.

See commit  43c7f49.

**Comment by djgroen** [comment]
@cspgdds Diana, could you perhaps check if INSTALL.md works for your purposes, given that you have a Mac platform? If so, then I can close this issue.

**Comment by cspgdds** [comment]
I updated instructions for MAC installation and provided description for additional issues that I encountered.
