### ISSUE TITLE
problems following the instructions in INSTALL.md

### ISSUE THREAD

**Issue by JamesSuter** [djgroen/FabSim3#122]
I'm following the instructions listed in INSTALL.md

So far, everything is OK, except for "LAMMPS testing on the local host"

After typing: 

fabsim localhost lammps_dummy:lammps_dummy,cores=1,wall_time=1:00:0

I get this error: 

[james@localhost] run: mkdir -p /Users/James/FabSim3/config_files; mkdir -p /Users/James/FabSim3/results; mkdir -p /Users/James/FabSim3/scripts; mkdir -p /Users/James/FabSim3/config_files/lammps_dummy
[james@localhost] rsync_project: rsync  -pthrvz  --rsh='ssh  -p 22  ' /Users/james/work/Fabsim3/config_files/lammps_dummy/ james@localhost:/Users/James/FabSim3/config_files/lammps_dummy
[localhost] local: rsync  -pthrvz  --rsh='ssh  -p 22  ' /Users/james/work/Fabsim3/config_files/lammps_dummy/ james@localhost:/Users/James/FabSim3/config_files/lammps_dummy
building file list ... done

sent 68 bytes  received 20 bytes  58.67 bytes/sec
total size is 678  speedup is 7.70
SCRIPT:  lammps
FabSim Error: could not find template file. FabSim looked for it in the following directories:  ['/Users/james/work/Fabsim3/plugins/FabDummy/templates', '/Users/james/work/Fabsim3/deploy/templates']
Traceback (most recent call last):
  File "/Users/james/work/FabSim3/bin/fabric_main.py", line 767, in main
    *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/james/work/Fabsim3/plugins/FabDummy/FabDummy.py", line 61, in lammps_dummy
    job(dict(script='lammps', wall_time = '0:15:0', lammps_input = "in.CG.lammps"),args)
  File "/Users/james/work/Fabsim3/base/fab.py", line 465, in job
    env.job_script = script_templates(env.batch_header, env.script)
  File "/Users/james/work/Fabsim3/deploy/templates.py", line 19, in script_templates
    result= "\n".join([script_template_content(name) for name in names]+commands)
TypeError: sequence item 1: expected str instance, NoneType found
Disconnecting from localhost... done.

I am presuming actually requires FabMD plugin, but this is not clear in the documentation.

**Comment by arabnejad** [comment]
it seems `lammps` template is missing, I will check it and back to you

**Comment by JamesSuter** [comment]
I've figured it out - it is because I hadn't installed the FabMD plugin. This requirement is not mentioned in INSTALL.md

**Comment by arabnejad** [comment]
INSTALL.md is updated

**Comment by djgroen** [comment]
Perhaps it's a bit strange to be installing FabMD as part of INSTALL.md, but the solution works for me. So I'm happy to close this for now, and we can always revisit this after M12.
