### ISSUE TITLE
Define additional functional tests for FabSim3 and plugins

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#125]
Currently, FabSim3 is very thin on functional tests. As part of this ticket, we should add five new functional tests, or incorporate five existing ones on CI. If you have done so, please leave a comment in this ticket referencing the test.

**Comment by arabnejad** [comment]
Different types of testing are covered by the latest [commit](https://github.com/djgroen/FabSim3/commit/99ac1fba7999bbd8b889cee6ebff1d4e293e4077) 
@djgroen  do you need more functional tests?

**Comment by djgroen** [comment]
No, this should be sufficient for M21. Closing this :).
