### ISSUE TITLE
Streamline PJ implementation

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#128]
In terms of pilot jobs, we have a few things to look at:
- [x] can we use it with dummy, or lammps jobs?
- [ ] how many users are using this functionality. It would be good if at least five of them get it conveniently working.

**Comment by arabnejad** [comment]
with dummy, I believe, there should not be any problem, 
however, for lammps, if the target machine has LAMMPS installed, i think there should not be a problem

**Comment by NicolasMonnier** [comment]
For my scalability study I tested dummy and It worked.

**Comment by djgroen** [comment]
Okay, that makes at least 3 users who get it working (me included). Good enough for me.
