### ISSUE TITLE
Organize FabSim3 hackathon

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#130]
When to do it, where, who to invite, what shall we focus on?

A rough aim would be the fall of this year.

**Comment by arabnejad** [comment]
maybe we can send an email to all FabSim, QCG and EasyVVUQ dev team with a empty agenda for now, ask them if they want to join this meeting and what shall we focus on  ?
and based on the agenda, asked those who want to join to fill the doodle poll for the location and date

**Comment by djgroen** [comment]
Okay, dates are set to September 23 and 24. I will organize it together with Robin.
