### ISSUE TITLE
Documentation needs to be made consistent

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#133]
We use ReadTheDocs now, but many documents are still in `doc` in Markdown, not in `docs` in .rst format. We should amend this, so that the docs are in one place...

**Comment by arabnejad** [comment]
after converting Markdown to rst format, should we use separate folder for each category, such as `/docs/container/` , `/docs/plugins/` and so on, or just convert all `.md` files to `.rst` and add into `docs` folder ?

**Comment by djgroen** [comment]
Let's make subfolders. I think it is cleaner that way.

**Comment by arabnejad** [comment]
I think [FabSim3 documentation](https://fabsim3.readthedocs.io/en/latest/
) is in a good shape now :grin: 
@djgroen do you have any suggestion to improve that? if not, I think we can close this issue

**Comment by arabnejad** [comment]
@djgroen all documentation in `doc` is already transferred to https://fabsim3.readthedocs.io,
so, I think we can close this issue now
