### ISSUE TITLE
Eagle job submission broken

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#136]
This commit broke the eagle job submission...

https://github.com/djgroen/FabSim3/commit/79ee770466be979fe3962a6142322a37996a3cca

I'm looking into this now, to see how to solve this, and make the design of VECMA and HiDALGO style access on one machine better.

**Comment by djgroen** [comment]
@arabnejad These are the commands that we need to get working:

Under VECMA (in order of descending priority):

> fab eagle flee_ensemble:validation,simulation_period=10
> fab eagle flee_ensemble:validation,simulation_period=10,PilotJob=True
> fab qcg flee_ensemble:validation,simulation_period=10

fab qcg flee_ensemble:validation,simulation_period=10,PilotJob=True

Under HiDALGO (in order of descending priority):

> fab eagle flee_ensemble:validation,simulation_period=10
> fab eagle flee_ensemble:validation,simulation_period=10,PilotJob=True

or alternatively:

> fab eagle-hidalgo flee_ensemble:validation,simulation_period=10
> fab eagle-hidalgo flee_ensemble:validation,simulation_period=10,PilotJob=True

Please do the work in the template-cleanup branch for now. Aim is to get it merged with master by the end of today.

**Comment by arabnejad** [comment]
I did a lots of changes  on FabSim (`template-cleanup` branch ) side and minor changes on FabFlee (`hamid-dev` branch)
please make sure you are using `FabFlee` from `hamid-dev` branch  

now, both `machines.yml` and `machines_user.yml`  are much clear

to run it (do all steps again on your accounts on VECMA and HiDALGO):
Under VECMA grant
 1. setup VirtuaEnv by
     > `fab qcg install_app:QCG-PilotJob,virtual_env=True` 
     > or 
     > `fab slurm_vecma install_app:QCG-PilotJob,virtual_env=True`
 2. setup Flee by
     > `fab qcg sync_flee` 
     > or 
     > `fab slurm_vecma sync_flee`
3. run tests by :
     > `fab qcg flee_ensemble:validation,simulation_period=10` 
     > `fab qcg flee_ensemble:validation,simulation_period=10,PilotJob=True` 
     > or 
     > `fab slurm_vecma flee_ensemble:validation,simulation_period=10` 
     > `fab slurm_vecma flee_ensemble:validation,simulation_period=10,PilotJob=True` 

Under HiDALGO grant
 1. setup VirtuaEnv by
     > `fab slurm_hidalgo install_app:QCG-PilotJob,virtual_env=True` 
 2. setup Flee by
     > `fab slurm_hidalgo sync_flee` 
3. run tests by :
     > `fab slurm_hidalgo flee_ensemble:validation,simulation_period=10` 
     > `fab slurm_hidalgo flee_ensemble:validation,simulation_period=10,PilotJob=True` 

we can changes remote machines names (i.e, slurm_hidalgo, slurm_vecma) if you don't like them ;)

**Comment by djgroen** [comment]
I believe this issue has been resolved, at least for now.
