### ISSUE TITLE
Improve presentation of FabSim3 examples with clear added value

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#146]
In discussions at UCL today we found out that we have positioned FabSim3 too much as a tool to support simple/single job execution, while neglecting its advantages in terms of creating simulations, analyzing data and creating complex workflows consisting of sequences of jobs and analysis.

In response to this, I feel that at the very least we need to make a clear and good-looking page explaining the advantages of FabSim3. Feel free to add ideas here on what to mention on this page.

**Comment by djgroen** [comment]
- auto-validation using our first VVP?

**Comment by arabnejad** [comment]
@djgroen  could you please add here a list of tasks that could be useful for this purpose ?

- [x] VVP `FabSim3/VVP/vvp.py`

**Comment by djgroen** [comment]
Added values are clearly shown on the landing page these days, so this ticket can be closed.
