### ISSUE TITLE
Analysis of csv output file

### ISSUE THREAD

**Issue by spamela** [djgroen/FabSim3#153]
Tried to run an example and easyvvuq crashed with strange error message...

**Comment by spamela** [comment]
,index,FF_0_input,T_0_input,R_geo_input,Volume,Current,run_id,ensemble_id
0,0,1.8874742966877194,1e-06,10.0,197.3787825,0.2038152,Run_1,Ensemble_1
1,1,1.0124764741676384,1e-06,10.0,197.37877319999998,0.1094206,Run_2,Ensemble_2
2,2,1.9249602978678861,1e-06,10.0,197.3787827,0.2078603,Run_3,Ensemble_3

**Comment by spamela** [comment]
import os
import easyvvuq as uq
import chaospy as cp

# 0. Setup some variables describing app to be run
#
#    gauss.py is in current directory and takes one input file
#    and writes to 'output.csv'.
cwd = os.getcwd()
input_filename = 'intear_input'
cmd = f"{cwd}/run_jorek.perl {input_filename}"
out_file = "output.csv"
# Template input to substitute values into for each run
template = f"{cwd}/intear.template"

# 1. Create campaign
my_campaign = uq.Campaign(name='jorek_intear', work_dir=".")

# 2. Parameter space definition
params = {
    "FF_0_input": {
        "type": "float",
        "min": 1.0,
        "max": 2.0,
        "default": 1.173
    },
    "T_0_input": {
        "type": "float",
        "min": 1.e-7,
        "max": 1.e-4,
        "default": 1.e-6
    },
    "R_geo_input": {
        "type": "float",
        "min": 9.0,
        "max": 11.0,
        "default": 10.0
    }
}

# 3. Wrap Application
#    - Define a new application (we'll call it 'gauss'), and the encoding/decoding elements it needs
encoder = uq.encoders.GenericEncoder(template_fname=template,
                                     target_filename=input_filename)

decoder = uq.decoders.SimpleCSV(
            target_filename=out_file,
            output_columns=['Volume', 'Current'],
            header=0)

my_campaign.add_app(name="jorek_intear",
                    params=params,
                    encoder=encoder,
                    decoder=decoder
                    )

# 4. Set a collation element
#    - This will be responsible for aggregating the results
collater = uq.collate.AggregateSamples(average=True)
my_campaign.set_collater(collater)

# 5. Specify Sampler
#    -  vary the `mu` parameter only
vary = {
    "FF_0_input": cp.Uniform(1.0, 2.0),
}

my_sampler = uq.sampling.RandomSampler(vary=vary)

my_campaign.set_sampler(my_sampler)

# 6. Get run parameters
my_campaign.draw_samples(num_samples=3,
                         replicas=1)

# 7. Create run input directories
my_campaign.populate_runs_dir()

# 8. Run Application
#    - gauss is executed for each sample
my_campaign.apply_for_each_run_dir(uq.actions.ExecuteLocal(cmd))

# 9. Collate output
my_campaign.collate()

my_campaign.get_collation_result().to_csv('error.csv')


# 10. Run Analysis
#     - Calculate bootstrap statistics for collated data
stats = uq.analysis.EnsembleBoot(groupby=["FF_0_input"], qoi_cols=["Current"])
my_campaign.apply_analysis(stats)
print("stats:\n", my_campaign.get_last_analysis())

**Comment by spamela** [comment]
This gave an issue. However, changing the number of replicas to 3 solved the problem...

**Comment by djgroen** [comment]
This is an EasyVVUQ issue, but I'm tagging the EasyVVUQ devs here just to make them aware of this...

**Comment by arabnejad** [comment]
@djgroen it seems that there is no update on this issue, I assume it is already fixed/solved by EasyVVUQ recent releases?

**Comment by djgroen** [comment]
I believe so yes.
