### ISSUE TITLE
setup_fabsim doing weird ssh connection

### ISSUE THREAD

**Issue by NicolasMonnier** [djgroen/FabSim3#155]
From a clean repository of FabSim3, I used hte following command :

`fab localhost setup_fabsim`

But FabSim3 is now trying to create an ssh connection (from my local computer to itself I guess ?). Is it suppose to happen ? It seems weird to me ...
The FabSim log : 

```
[your-username@localhost] Executing task 'setup_fabsim'
To set up your SSH keys, you will be logged in to your
local machine once using SSH. You may be asked to provide your password once to facilitate this login.
local id_rsa key already exists.
[ localhost ] local : ssh-copy-id -i ~/.ssh/idçrsa.pub your-username@localhost 2> ssh_copy_id.log
your-username@localhost's password : 
```

**Comment by arabnejad** [comment]
Hi @NicolasMonnier 
you need to set `username` parameters in the `FabSim3/deploy/machines_user.yml` file, did you do that ?
```
default:
  . . .
  username: "your-username"
  . . .
```

**Comment by NicolasMonnier** [comment]
@arabnejad Indeed, I forgot to do that ! 
It's working now.
