### ISSUE TITLE
Optimize Replica functionnality

### ISSUE THREAD

**Issue by NicolasMonnier** [djgroen/FabSim3#157]
Here is a suggestion to optimize the Replica functionnality. 

Currently Fabsim3 is doing something like this when replica functionnality is set:

```
Job():
    for i in Replica:
        Send Jobname to remote as Jobname_i
        Launch Jobname_i on remote
```

Since the replicas of a Job are suppose to be the same, we're sending the same data X time. Does it make sense to do something like that instead ? 

```
Job():
    if Replica:
        Send Jobname to remote as Jobname_1
        on cluster run :  {for i in {number of replicas}; do cp Jobname_1 Jobname_$i ; done}
```

if we consider that doing a local copy on a cluster is faster than sending using an ssh connexion, that would proably save some time.

What do you think ? We can discuss about it at UCL anyway.

**Comment by arabnejad** [comment]
@djgroen about Nicolas suggestion, I think it requires to have a job as pre-preparation which generate those replicas and then submit jobs to cluster or keep ssh alive to remotely run this replica functionality
what do you think @djgroen , should we close this issue or you want to give a try and implement it ?

**Comment by djgroen** [comment]
I think this has now been addressed.
