### ISSUE TITLE
pip3 install fabsim3

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#162]
Hi all.

The title says it all. Could we possibly make it work, given that plugins come from GitHub repos? Or would it make our tool needlessly complicated in terms of structure?

Several users have requested it, so I think we should give it a serious consideration now.

**Comment by djgroen** [comment]
@arabnejad and I had a discussion on this, and considered four usage scenarios:

1. Users with 1 Fabsim installation (with one or more plugins), who are not planning to develop on plugins and push changes to GitHub.
2. Users with 1 Fabsim installation, who are planning to develop on plugins and push changes to GitHub.
3. Users with >1 Fabsim installations, who are not planning to develop on plugins and push changes to GitHub.
4. Users with >1 Fabsim installations, who are planning to develop on plugins and push changes to GitHub.

In our opinion, a `pip install` would:
- help users in category 1, but these are not really the target users for FabSim3, and will already be catered for by QCG-Now.
- not help users in category 2, because any version update (pip install --update) would normally wipe out all their plugins and customized content. We could work around this by letting them manage plugins, results and config files outside of the Python package, but this requires a considerable amount of administration, and largely eliminates the advantages of using `pip`.
- not matter for category 3, because we cannot think of any users in category 3.
- not be relevant to category 4, because all people we know of in this category are core developers of the base FabSim toolkit, and the ones who can install it already with ease.

Based on these considerations, we conclude that `pip install` is not the correct solution for the installation difficulties that alpha users currently experience. 

As an alternative, we propose the following two installation steps:
1. `git clone https://www.github.com/djgroen/FabSim3.git`
2. `python3 setup_fabsim`

The idea is that step 2 automates more things than the current installation, such as:
- [] fill in machines_user.yml with sensible default values.
- [] configure FabSim3 correctly to support the operating system platform of the local machine, making changes for instance to work correctly on OSX.
- [] including adding ssh-add for OSX.
- [] enable direct access to the `fabsim` command from anywhere on the file system (i.e. needs to be in PATH).
- [] set the PYTHONPATH correctly.

**Comment by wedeling** [comment]
I am in category 2, and if a pip update would wipe out my plugins I would indeed not be in favor of this. The alternative sounds nice, seems easier than the current install procedure.

**Comment by arabnejad** [comment]
Hi @wedeling 
`python3 setup_fabsim` functionality is already provided, you can find it here
https://github.com/djgroen/FabSim3/blob/FabSim3_automated_installation/configure_fabsim.py
