### ISSUE TITLE
Debugging FabSim3

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#165]
https://github.com/djgroen/FabSim3/blob/7721b1a8657750a53fecd766ad40116c0ddfd7ce/deploy/machines.yml#L238

Okay, there are a number of really ugly bugs that have crept into FabSim3, and that are causing huge problems. Please find one of them above.

I will fix this one now, and I already fixed two others previously.

**Comment by djgroen** [comment]
Just to elaborate on this one: Eagle has 28 cores per node. Setting this value to 1 as a default is causing enormous CPU cycle wastage.

**Comment by arabnejad** [comment]
I think we can close this issue, `corespernode` values are updated for each corresponding available remote machine in `machines.yml`
