### ISSUE TITLE
/bin/true file required for tests, but not present on macs

### ISSUE THREAD

**Issue by velocirobbie** [djgroen/FabSim3#168]
`fab localhost dummy:dummy_test` raises this error:

```
....
[robertsinclair@localhost] out: /bin/bash: /bin/true: No such file or directory
[robertsinclair@localhost] out: 
Fatal error: run() received nonzero return code 127 while executing!
```

seems to come from the dummy run prefix. See deploy/machines.py:218

**Comment by velocirobbie** [comment]
this happens with `fab localhost lammps:lammps_test1` (with FabMD plugin) as well, so I'm less sure of the source of this error

**Comment by arabnejad** [comment]
Please update this line in /FabSim3/deploy/machines.py
 
'/bin/true’ ---- changed to -> '/bin/true || true'
 
https://github.com/djgroen/FabSim3/blob/65ed444ee559fa59803e3f32c4804658091465a1/deploy/machines.py#L218

**Comment by velocirobbie** [comment]
I can now run the dummy test, do you want to put this in master as a bug fix?

**Comment by arabnejad** [comment]
I did it already :)
