### ISSUE TITLE
Summary of Key M18 comments

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#169]
- Unclear. Even though I would like to use this in the future, it is not clear how this toolkit can benefit my workflow and it seems to be adding extra steps.
- 

About VECMAtk in general:
- Examples including integration with different HPC platforms and softwares. 
- A more down-to-earth documentation for absolute beginners.
- It is unclear what are the limitations to the tools offered by VECMAtk. These need to be discussed and written down clearly.
- Documentation should be very simple to understand and examples should be very basic to explain a concept well.
- It would nice to have a oneline installation of the toolkit
- Maybe a good option would be to create a short introduction to VECMAtk, e.g. in a form of a video. I think that with the currently presented overview it could be difficult to get an idea of the toolkit. Of course a user gets information about particular components, but I think that there is no top-level guidance when and for what use-cases these components should be used.

**Comment by arabnejad** [comment]
@djgroen I think with M24 release we already cover all these points, if not, we can close this and open a new one for M30 release for those that are not addressed yet

**Comment by djgroen** [comment]
Many of these comments have been addressed. The one about more accessible tutorials is an ongoing point, and we will make further changes VECMA-wide to facilitate that one.
