### ISSUE TITLE
fixes multi-threading functionality

### ISSUE THREAD

**Issue by arabnejad** [djgroen/FabSim3#174]
in case of using ensemble functionality with a single replica, there is some mismatch between the job script file name and its saved folder, for instance 

```
ssudan_ccamp_eagle_hidalgo_4_Run_198.sh  ---saved in folder---> Run_208
```
I think a race condition occurs for `env.label` variable when the script file name generated

**Comment by eraffin** [comment]
Thanks @arabnejad
