### ISSUE TITLE
Submit ensemble job when SWEEP folder located on remote machine

### ISSUE THREAD

**Issue by arabnejad** [djgroen/FabSim3#192]
Currently, to run an ensemble job, we only look at the localhost folder and generate the run scripts.
in case of having SWEEP folder on remote machine, we need to list folder name from remote machine

**Comment by arabnejad** [comment]
This can be closed by  https://github.com/djgroen/FabSim3/commit/dab51a7e31e3c3507cf988a7102bc1f5f1eea476

In order to specified where should be looked into when we call `run_ensemble` function, a new input arg, `sweep_on_remote=True` should be passed by developer, the default value is `False`, so there will be no problem with previous usage of `run_ensemble` in plugins

**Comment by djgroen** [comment]
Hi Hamid. Have you incorporated this new feature in the FabSim3 documentation as well?

**Comment by arabnejad** [comment]
This new feature is added and explained in the FabSim3 documentation
https://fabsim3.readthedocs.io/en/latest/fabsim3api.html#run-ensemble-config-sweep-dir-sweep-on-remote-false-execute-put-configs-true-args
