### ISSUE TITLE
Adds option to install plugin with branch name 

### ISSUE THREAD

**Issue by arabnejad** [djgroen/FabSim3#194]

**Comment by arabnejad** [comment]
closed by https://github.com/djgroen/FabSim3/commit/b6ceb7970cd927ea21b40e0612d6154942b62a73

I added the `branch` input arg when we run `install_plugin` task
```sh
fabsim localhost install_plugin:<plugin_name>,,branch="<branch_name>"
```

**Comment by djgroen** [comment]
Same for this one: did you add this option to the documentation as well?

**Comment by arabnejad** [comment]
The instruction is added to https://fabsim3.readthedocs.io/en/latest/plugins.html
