### ISSUE TITLE
interfacial IBI about density profile

### ISSUE THREAD

**Issue by zhoumengyu0704** [djgroen/FabSim3#197]
Hello! I have learned that Fabsim can perform IBI, now I want to calculate out the interfacial nonbonded potential of nanocomposites, the density profile of polymer along the surface of filler was considerd as target distribution. With Fabsim, can I get the potential energy of the interface by IBI based on  the density profile ? If possible, can you tell me the general flow of the user-defined script？I am looking forward to your reply.Thanks very much!

**Comment by djgroen** [comment]
Hi there! The IBI calculation functions are all part of the FabMD plugin, which you can find at https://www.github.com/UCL-CCS/FabMD. Would you perhaps be able to raise your issue there, so that the developers there can help you? :)

Cheers!
-Derek

**Comment by zhoumengyu0704** [comment]
Thanks very much!











At 2021-04-08 20:56:09, "Derek Groen" ***@***.***> wrote:

Hi there! The IBI calculation functions are all part of the FabMD plugin, which you can find at https://www.github.com/UCL-CCS/FabMD. Would you perhaps be able to raise your issue there, so that the developers there can help you? :)

Cheers!
-Derek
