### ISSUE TITLE
Using a separate subdirectory for FabSim3 API

### ISSUE THREAD

**Issue by arabnejad** [djgroen/FabSim3#203]
### Is your feature request related to a problem? Please describe.

For long term support, I think it would be better we follow a formal python project structure and use a separate subdirectory for all FabSim3 codes. 
One of our user had an issue before regarding the current structure : assume, we have a same python package as the folder name in FabSim3, for example, a [`base`](https://pypi.org/project/base/) py package is installed in your system, in this case
```python
from base.fab import *

```
which is using in our plugin will raise an `import` issue.

### Describe the solution you'd like

I think it would be better if we keep our FabSim3 python code files in a **separate subdirectory**, and keep the repository's root directory for other stuffs such as installation scripts, py tests, and all manner of other things that aren't actually part of the source code.

what do you think @djgroen ?

**Comment by djgroen** [comment]
I largely agree, and in making these changes we need to ensure that we still have a simple-looking import command for users that want to rely on the FabSim3 python functions. I guess this could be accomplished by changing the path that should be added to the Pythonpath perhaps?

**Comment by arabnejad** [comment]
yes, we only need to make sure all plugins use the new PATH for FabSim3 API

* for example, instead of 
  ```python
   from base.fab import *
   ```
   we should use
  ```python
   from fabsim.base.fab import *
   ```

I am going to do apply this change in the FabSim3 repo and also do some tests, then for all plugins that we have access, the FabSim3 API access will be updated, for others I will inform the developers to follow the same structure and update their plugins
