### ISSUE TITLE
README.md refers to non-existing INSTALL.md file

### ISSUE THREAD

**Issue by matt-graham** [djgroen/FabSim3#207]
### Suggestion on the FabSim3 documentation

> Provide a clear and concise description of what is missing or what you need to be added in the FabSim3 documentation

The `README.md` file in the root of the repository contains the text

> For instructions on how to install and test FabSim, please refer to `INSTALL.md`.

Currently there is no `INSTALL.md` file in the root of the repository or any of the subdirectories that I can see. Perhaps this is meant to point at [`docs/installation.md`](https://github.com/djgroen/FabSim3/blob/master/docs/installation.md) instead?

**Comment by djgroen** [comment]
Hi Matt.

Thanks a lot for flagging this up! I briefly considered linking to the readthedocs, but then figured a local link indeed works best here.

The change should now be there :)

Thanks again for your help on this!
