### ISSUE TITLE
Storing / passing passwords using `sshpass` in clear text is a potential security issue

### ISSUE THREAD

**Issue by matt-graham** [djgroen/FabSim3#208]
The example `machines_users.yaml` entry for ARCHER2 is given as

https://github.com/djgroen/FabSim3/blob/292fa726bdffaf66abf786c932fac4c5a6382519/fabsim/deploy/machines_user_example.yml#L49-L53

This seems to be suggesting to users to store their ARCHER2 password in clear text in the configuration file? If so this is a bad idea from a security standpoint as anyone with access to that machine would be able to view the password. Additionally as the password is written directly as the `-p` argument to `sshpass` at various points (and in some cases printed to `stdout`), for example

https://github.com/djgroen/FabSim3/blob/292fa726bdffaf66abf786c932fac4c5a6382519/fabsim/base/manage_remote_job.py#L47-L50

https://github.com/djgroen/FabSim3/blob/292fa726bdffaf66abf786c932fac4c5a6382519/fabsim/base/fab.py#L133-L140

https://github.com/djgroen/FabSim3/blob/292fa726bdffaf66abf786c932fac4c5a6382519/fabsim/base/fab.py#L263-L272

https://github.com/djgroen/FabSim3/blob/292fa726bdffaf66abf786c932fac4c5a6382519/fabsim/base/fab.py#L868-L877

I believe that the password will also appear in clear text in the running process list, so could be seen by any other user of the system by just running `ps`. Even if this is only used on personal machines with no shared access there is still a risk of there being exposure via malware with access to the process list or file system. 

The `man` page for `sshpass` includes the following security warning

```
SECURITY CONSIDERATIONS
       First and foremost, users of sshpass should realize that ssh's insistance on only getting the password in‐
       teractively is not without reason. It is close to impossible to securely store the password, and users  of
       sshpass  should  consider  whether  ssh's public key authentication provides the same end-user experience,
       while involving less hassle and being more secure.

       The -p option should be considered the least secure of all of sshpass's options.  All system users can see
       the  password  in the command line with a simple "ps" command. Sshpass makes a minimal attempt to hide the
       password, but such attempts are doomed to create race conditions without  actually  solving  the  problem.
       Users  of  sshpass  are encouraged to use one of the other password passing techniques, which are all more
       secure.

       In particular, people writing programs that are meant to communicate the password programatically are  en‐
       couraged to use an anonymous pipe and pass the pipe's reading end to sshpass using the -d option.
```

I think in general using `sshpass` is probably a bad idea here, because as the `man` page suggests it is very difficult to use it in a way which doesn't create security issues.

It looks like the option to use `sshpass` was added in the commit 3bb8dad5faa7aeb62dbe3b3f6a0960e1c59f7e24 which implies previously the password prompt would appear and require manual entry on running commands requiring access to a password-protected remote machine? I think even if less convenient from the user perspective this would be preferable to the current approach.

**Comment by arabnejad** [comment]
Hi @djgroen and @matt-graham 
the reason for this was : in case of having large ensembles runs, you have to type the password for each file

but, if you want to disable `sshpass` , just simple disable it with 
```yaml
 archer2: 
   username: "<your-username>" 
   manual_sshpass: false # <<<< --- this will disable using sshpass
   job_wall_time : "0-00:10:00" 
```
and you should be promoted to enter the password

**Comment by matt-graham** [comment]
Hi @djgroen  and @arabnejad. Thanks both for your responses

@arabnejad that's useful to know to regards to disabling `sshpass` - I would be inclined to have this as the default example in the `machines_user_example.yml` file perhaps with a note in the documentation saying an an alternative is to use `manual_sshpass: true` with password in file but with a warning that about the security implications of this and recommendation to for example make sure the file is only user-readable and to only do this on a machine which you have sole use of.

I said to @djgroen on Slack that I will have a look and see if there is alternative way of doing this which might allow using a password manager or similar to store the password and/or requiring entry of the password just once

**Comment by matt-graham** [comment]
From a bit of research I think a possible solution would be to use [OpenSSH's multiplexing functionality](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing) to persist an initial connection which requests the user's password and then re-use this same open connection for subsequent `ssh` / `rsync` commands without requiring entering the password each time. [This approach is proposed to solve a similar issue of caching SSH passwords on `superuser`](https://superuser.com/a/1362903). 

The easiest approach from the perspective of not having to add anything on the FabSim3 side, would be to just get users who need to use remote machines with password based authentication to manually set up their `.ssh/config` file with the relevant configuration options (assuming they are using the OpenSSH client), for example adding something like the following

```
Host archer2
   HostName login.archer2.ac.uk
   ControlPath ~/.ssh/%r@%h:%p
   ControlMaster auto
   ControlPersist 30m
```

which would automatically open a connection in background on first `ssh` command, where password would need to be entered, and then keep this open in background for 30 minutes. I've tested and this does seem to work with ARCHER2 suggesting the relevant features are enabled on the server side. A guide to doing this could added to the documentation.

More integrated solutions would be to either provide a script to automate setting the relevant configuration up or adding a option to have the relevant `ssh` / `rsync` commands in FabSim3 directly pass the required `-o ControlMaster=yes -o ControlPath="$HOME/.ssh/%r@%h:%p"` arguments to set up an initial connection and ` -o ControlPath="$HOME/.ssh/%r@%h:%p` to reuse the connection in subsequent commands.

**Comment by djgroen** [comment]
We've got comprehensive documentation on multiplexing now. SSHpass support may be removed altogether soon, and it is already absent in the docs.
