### ISSUE TITLE
Installation instructions list deprecated fabric3 package as dependency

### ISSUE THREAD

**Issue by matt-graham** [djgroen/FabSim3#209]
### Suggestion on the FabSim3 documentation

The installation instructions in `docs/installation.md` list `fabric3==1.13.1.post1` as one of the dependencies for FabSim3, however the current `configure_fabsim.py` script checks for the presence (and installs if not already present) the package `fabric2` instead, and `fabric3` seems to be deprecated - the [PyPI page for `Fabric3` package](https://pypi.org/project/Fabric3/) links to [this GitHub repository](https://github.com/mathiasertl/fabric/) which states
> The excellent [Fabric](http://www.fabfile.org/) now finally supports Python3, there is thus no longer a use for this project. Please use mainline Fabric instead.

To avoid having to maintain the project dependencies in multiple different places it might be better to have the `requirements.txt` file in the repository root as the single place this is defined and then this file either included in the relevant documentation page for example using [this `mkdocs` plug in](https://pypi.org/project/markdown-include/) or that page automatically generated and populated with current value of `requirements.txt` one each documentation build.

**Comment by djgroen** [comment]
This mismatch is resolved, although we may still want to automate the mapping of requirements.txt to the documentation.
