### ISSUE TITLE
Host name resolve issue

### ISSUE THREAD

**Issue by alirezajahani60** [djgroen/FabSim3#210]
When I want to submit jobs to Archer2, even after setting up multiplexing, I need to enter my password several times.

**Comment by alirezajahani60** [comment]
> When I want to submit jobs to Archer2, even after setting up multiplexing, I need to enter my password several times.

I noticed I specified the wrong name for remote entry in the machines_FabFlee_user.yml file. So I changed it from "login.archer2.co.uk" to just "archer2" and it worked.

**Comment by djgroen** [comment]
This one is solved :).
