### ISSUE TITLE
Add time stamp variable

### ISSUE THREAD

**Issue by tkoskela** [djgroen/FabSim3#211]
### Is your feature request related to a problem? Please describe.

There is not time stamp variable in `env.yml`. It would be nice to have to keep results from being overwritten.

**Comment by djgroen** [comment]
@tkoskela Sorry for solving this so late!

We did have a variable like that earlier, but somewhere along the way we lost it. So I created a new one:
`local_system_time: 1680179082`

Hope this works for your purposes!
https://github.com/djgroen/FabSim3/commit/6ffa8a134ef98cbd2ba972017aa09a90cdc9d38d
