### ISSUE TITLE
Python 3.6 reached end-of-life on Dec 12, 2021

### ISSUE THREAD

**Issue by arabnejad** [djgroen/FabSim3#215]
Python 3.6 reached [end-of-life on Dec 12, 2021](https://peps.python.org/pep-0494/#lifespan), and that is why the pipeline is broken.
Since, there will be no supporting it with new versions of GitHub hosted runners (we used Ubuntu:latest version), I think we need to delete it from our test workflow. To do that, just delete python 3.6 from list of python-version in [GitHub workflow yml file ](https://github.com/djgroen/FabSim3/blob/master/.github/workflows/Pytests.yml#L20)
However, we can still test it with Python 3.6, on ubuntu-20.04.

What do you think @djgroen, should we remove it or keep it ?

**Comment by djgroen** [comment]
Hi Hamid,

I would be in favour of removing it :).

Cheers!
-Derek

**Comment by djgroen** [comment]
Thanks for removing it Hamid!
