### ISSUE TITLE
FabSim uses templates defined in one plugin in another

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/FabSim3#220]
Suppose we have a plugin called FabABC which has its own set of templates: tempA, tempB, tempC. In this situation, if I create a new plugin FabXYZ with its own templates: tempX, tempY, tempZ. 

Next, In FabXYZ.py, I use (by mistake) the command

job(dict(script='tempA', wall_time='0:15:0', memory='2G',label=qwerty), args)

Then, the code, instead  of throwing an error, uses the template tempA defined in FabABC.

This causes a not of confusion in debugging a new plugin that was created using an old plugin as a template.

**Comment by djgroen** [comment]
This is a known issue, and I think can be circumvented by responsible plugin design, at least for the time being.
