### ISSUE TITLE
Default machine configuration for ARCHER2 tries to `cd` to non-substituted template path

### ISSUE THREAD

**Issue by matt-graham** [djgroen/FabSim3#256]
### Describe the bug

When trying to run a task on `archer2` I noticed that the `sbatch` command used to submit the job script to the scheduler is always preceded by a `cd /work/$project/$project/$username` which appears to be trying to change directory in to a templated path which hasn't had the relevant templated variables substituted. I think this arises because the `job_dispatch` variable for `archer2` is set by default as the following

https://github.com/djgroen/FabSim3/blob/62ca215febb2ef5112a7f5a59574ae3db465a1e7/fabsim/deploy/machines.yml#L501

and this is then passed to `template` in

https://github.com/djgroen/FabSim3/blob/62ca215febb2ef5112a7f5a59574ae3db465a1e7/fabsim/base/fab.py#L1036

however this only substitutes `$job_dispatch` for its definition, and doesn't deal with the inner variable references.

### Executed steps

1. Run a `fabsim` task on `archer2` - for example `fabsim archer2 neso:two_stream`
2. Check commands executed in _job submission phase_

### Expected behavior

The `cd` command should instead be given the path with all template substitutions applied as argument.

### Platform details

 - OS: Ubuntu 22.04
 - FabSim3 version: 3253696
 - Python version: 3.10.4

### Possible Solution

 It looks like `template` accepts a `number_of_iterations` argument (defaulting to 1) which allows dealing with recursively defined templates, so possibly a resolution here would be to just set this argument to 2 in 

https://github.com/djgroen/FabSim3/blob/62ca215febb2ef5112a7f5a59574ae3db465a1e7/fabsim/base/fab.py#L1036

**Comment by djgroen** [comment]
Hi Matt.

Did you define your username and project variable in `machines_user.yml` as indicated in the instructions?

![image](https://github.com/djgroen/FabSim3/assets/4508093/7bc072e6-5809-48ef-ab40-7957a90bda0a)

**Comment by matt-graham** [comment]
Yes I've got all the relevant user-specific machine configuration set. It's not that the variables are being substituted with default values / empty strings, it's that the variables aren't being substituted at all, so the raw template string is being used as the `cd` command argument.

**Comment by matt-graham** [comment]
> It looks like `template` accepts a `number_of_iterations` argument (defaulting to 1) which allows dealing with recursively defined templates, so possibly a resolution here would be to just set this argument to 2 in
> 
> https://github.com/djgroen/FabSim3/blob/62ca215febb2ef5112a7f5a59574ae3db465a1e7/fabsim/base/fab.py#L1036

I think this would be a solution but I'm not sure if setting `number_of_iterations=2` will lead to problems for configurations in which `job_dispatch` variable doesn't have nested variable references in it (or will it just have no additional effect in this case)?

**Comment by djgroen** [comment]
We have not had the need to use `number_of_iterations=2` before in FabSim. I think most likely some important parts of the environment may not have been loaded in your custom neso function. You can check this by looking at the env.yml file in the resuts folder of your neso job :).

**Comment by djgroen** [comment]
It may well be that we need to clarify better how to load parts of the env into custom FabSim functions in the documentation, by  the way ;)

**Comment by matt-graham** [comment]
The environment variables are definitely set - they're both in the `env.yml` file output in the `results` directory and when I step through the task execution with a debugger they are present in `env`.

**Comment by matt-graham** [comment]
Just to clarify - this doesn't actually stop job being submitted with `sbatch` as `cd /work/$project/$project/$username` will get resolved to `cd /work` (assuming there aren't `project` / `username` environment variables set on ARCHER2 shell being used) as the non-defined variables get replaced with empty strings, meaning `cd` doesn't return an error code and so the `sbatch` command will still run.

**Comment by djgroen** [comment]
I just checked your neso function in FabNESO. Normally, we use an `update_environment(args,...)` function at the start to make sure all the relevant flags are passed to the environment, and various strings are substituted correctly. However, I do not find that call at the start of your neso function, so perhaps that may be causing this issue?

It may be that you do not wish to use the update_environment call at the start, but it is also provided in the `dummy` call in FabDummy, so if you choose not to use it you may have to use an alternative for it.

![image](https://github.com/djgroen/FabSim3/assets/4508093/c11bef0c-e9f1-4fa2-9ad1-c50b455de5d1)

**Comment by matt-graham** [comment]
`update_environment` as far I can tell just updates the global `env` dict-like with the entries in the passed dictionary or dictionaries:

https://github.com/djgroen/FabSim3/blob/62ca215febb2ef5112a7f5a59574ae3db465a1e7/fabsim/deploy/machines.py#L211-L213

So calling `update_environment` at the beginning of the `neso` task with a dictionary of the arguments of the task, would just add those arguments (`config`, `solver`, `conditions_file_name`, `mesh_file_name` and `parameter_overrides`) to `env` before the `with_config(config)` and `execute(put_configs, config)` calls. As neither of those calls makes use of any of those argument values, I don't think calling `update_environment` with the task arguments before these would make any difference to the behaviour. The `job` function in `fabsim.base.fab` itself calls `update_environment` with the passed arguments as one of its first statements

https://github.com/djgroen/FabSim3/blob/62ca215febb2ef5112a7f5a59574ae3db465a1e7/fabsim/base/fab.py#L587

so at this point the arguments specified in dictionary passed to `job` (`script`, `neso_solver`, `neso_conditions_file` and `neso_mesh_file`) will be added to the environment, so this from this point on we should get the equivalent behaviour to having called 

```Python
    fab.update_environment(
            {
                "script": "neso",
                "neso_solver": solver,
                "neso_conditions_file": conditions_file_name,
                "neso_mesh_file": mesh_file_name,
            }
    )
```

in the `neso` task function before calling `job`.

I have verified that adding an `update_environment` call to the `neso` task (either with actual argument names or the adjusted version above which adds `neso_` prefix to the NESO specific options minimize the risk of name clashes) at the beginning does make any difference to the bug being reported here.

**Comment by matt-graham** [comment]
A minimum reproducing example which replicates the problem:

```Python
from fabsim.base.fab import update_environment
from fabsim.deploy.machines import template

update_environment(
    {
        "username": "mgraham",
        "project": "e723",
        "job_dispatch": "cd /work/$project/$project/$username ; sbatch"
    }
)
job_script = "test"
print(template("$job_dispatch {}".format(job_script)))
```
outputs

```
cd /work/$project/$project/$username ; sbatch test
```

Changing final line to `print(template("$job_dispatch {}".format(job_script), number_of_iterations=2))` instead outputs

```
cd /work/e723/e723/mgraham ; sbatch test
```

**Comment by djgroen** [comment]
Hi Matt,

I am a bit puzzled, but if you are able to solve it with `number_of_iterations=2` then I think it is best to go with that solution.

I am puzzled in particular, because I do not (yet) understand why this problem occurs in your `neso` task, but not in the `dummy` task on FabDummy, or e.g. the `flee` task in FabFlee. I also have that environment variable set the same way, and don't experience this particular issue.

Your test script reproduces the issue on my machine too, but those FabSim cmds like `dummy` and `pflee` work as normal.

**Comment by matt-graham** [comment]
> Your test script reproduces the issue on my machine too, but those FabSim cmds like `dummy` and `pflee` work as normal.

Just to check when you say the `dummy` and `pflees` commands work as normal - do you mean they run successfully or that they run successfully _and_ the `cd ...` command run in the _job submission_ phase uses the correct subsituted path? The issue here doesn't cause the `neso` task to fail on ARCHER2 for me either (see https://github.com/djgroen/FabSim3/issues/256#issuecomment-1860339349 for explanation) but the `cd` command does not work as intended.

**Comment by djgroen** [comment]
Ah.... I see the bug you're referring to now! Thank you for clarifying it.

I have the very same bug in my terminal actually, but indeed it never affected any job submission functionality or other, as batch commands tend to work from anywhere. Hence I had not noticed it before.

That is an interesting issue, and I think your proposed solution makes perfect sense here :).
