### ISSUE TITLE
If fabsim3 has spaces in the path

### ISSUE THREAD

**Issue by garypolhill** [djgroen/FabSim3#269]
Found a bug? Please fill out the sections below. 👍

### Describe the bug

Cannot cope with spaces in paths.

### Executed steps

1. step 1 install fabsim at a path with directories with spaces in the name (my case: "/Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3"
2. step 2 fabsim localhost install_plugin:FabDummy
3. you get it...

### Expected behavior

No problems with that

### Relevant logs and/or media (optional)

If applicable, add screenshots to help explain your problem. Terminal transcript follows:

% fabsim localhost install_plugin:FabDummy
[Executing task] install_plugin
[local] mkdir -p /Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/plugins
[local] rm -rf /Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/plugins/FabDummy
[local] git clone https://github.com/djgroen/FabDummy.git /Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/plugins/FabDummy
fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    --reject-shallow      don't clone shallow repository
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    --recursive ...       alias of --recurse-submodules
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    --server-option <server-specific>
                          option to transmit
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering
    --also-filter-submodules
                          apply partial clone filters to submodules
    --remote-submodules   any cloned submodules will use their remote-tracking branch
    --sparse              initialize sparse-checkout file to include only files at root
    --bundle-uri <uri>    a URI for downloading bundles before fetching from origin remote

Traceback (most recent call last):
  File "/Users/gary/git/FabSim3/fabsim/bin/fabsim", line 46, in <module>
    sys.exit(fabsim_main.main())
             ^^^^^^^^^^^^^^^^^^
  File "/Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/fabsim/base/fabsim_main.py", line 162, in main
    env.exec_func(*env.task_args, **env.task_kwargs)
  File "/Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/fabsim/base/decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/fabsim/base/setup_fabsim.py", line 65, in install_plugin
    local(
  File "<@beartype(fabsim.base.networks.local) at 0x1018e3b00>", line 54, in local
  File "/Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/fabsim/base/networks.py", line 55, in local
    raise RuntimeError(
RuntimeError: 
local() encountered an error (return code 129)while executing 'git clone https://github.com/djgroen/FabDummy.git /Users/gary/Library/CloudStorage/OneDrive-TheJamesHuttonInstitute/Teaching/HPC ABM Teaching Materials/hpc-abm/FabSim3/plugins/FabDummy'

### Platform details (optional)

 - OS: [e.g. Linux, MacOS] MacOS
 - FabSim3 version: fabsim3 does not respond to --version / -version / -v. MD5 (fabsim/bin/fabsim) = beb989420c6d7c38e32e184b25130323
 - Python version:Python 3.11.3

### Possible Solution (optional)

A clear and concise description of your suggestion to resolve it.

**Comment by djgroen** [comment]
Hotfix attempt with ed02b7fba0899f82ddf92d4b586e022db5bffe79

Please pull the latest version and let me know if that works for you :).

**Comment by garypolhill** [comment]
Thanks
