### ISSUE TITLE
Questioning the reason of the directory 'lists/'

### ISSUE THREAD

**Issue by jomichaelis** [djgroen/FabSim3#290]
Disclaimer: This is for the sake of clean file structure only.

## Problem
I have been wondering what the real deal behind the text files in the `list`-directory is for quite some time now.
There exist 4 files:
- machines.txt
- standalone_tasks.txt
- tasks_args.txt
- tasks_with_args.txt

First I supposed they would be required for the command `fabsim -l machines` or `fabsim -l tasks`, however this is not the case.
Both lists are directly assembled from the corresponding machine-`.yml`-files and the Python files where core- & plugin-tasks are defined.
Secondly, I examined whether the text files would help the autocompletion script to autocomplete user inputs, but again, both `autocompletion.sh` and `autocompletion.py` are not referencing the text files.

I checked with several external plugins, but none of them references the text files either.
Even if this was the case, the files might better be included in the plugin itself instead of the FabSim3 repository.

## Solution Proposal
Having deleted the directory for a couple of days now, I was unable to notice any malfunctioning of FabSim3 and I'd thus like to suggest to remove the text files and the `list` directory entirely.

The removal of the files does not add any functionality, however it does not break any core functionality either.
And for new users, the text files might be confusing and hard to understand their reason to exist.

**Comment by djgroen** [comment]
@arabnejad originally developed the autocompletion. Hamid, do you agree with @jomichaelis that these can be removed?

Cheers!
-Derek

**Comment by arabnejad** [comment]
Hi @jomichaelis @djgroen 

I have no idea why this folder is added :flushed:

here is the commit which added this folder and text files https://github.com/djgroen/FabSim3/commit/1bd555f63189af65bac2922aa94d3cfe2b4d3356#diff-3864864b2f7f53aa3300b24344429177fa950f0bfe615372f8073f66120b7e41

I'm not sure of the purpose or reasoning behind including those text files :confused:

@djgroen, I totally agree with @jomichaelis, It would be best to remove those files and explore a more effective solution to provide autocompletion support for FabSim commands. As part of packaging FabSim for pip, I will investigate options to implement a better approach :smiley:

**Comment by djgroen** [comment]
@arindamsaha1507 I think you've added in this directory. Could you perhaps have a look at this issue and let me know if you think we can remove it?

**Comment by arindamsaha1507** [comment]
Hi Derek and others,

I think I added this folder as a re-organizing attempt while we were developing autocomplete. I think it can be removed and more effective auto-complete solutions be explored. :)

**Comment by jomichaelis** [comment]
The autocompletion works as intended, and from analyzing the `autocomplete.py` script, I understand the script extracts machines and tasks from the `.yml` and `.py` files correctly.
Thank you for your contributions!
