### ISSUE TITLE
Documentation required for manually setting up a FabSim3 ensemble.

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#302]
### Suggestion on the FabSim3 documentation

Currently, there are instructions on running ensembles as part of the FabDummy tutorial in testing. However, we do not clearly explain how to manually construct an ensemble, using the `SWEEP` directory. This needs to be added.

**Comment by mzrghorbani** [comment]
Hi team,

I’ve updated testing.md to include a section on manually constructing ensemble jobs using the SWEEP directory. This addition provides step-by-step instructions for configuring and running ensembles with run_ensemble, including explanations of each parameter and example usage. It should help users understand how to set up and submit their own ensembles effectively.

Let me know if any further adjustments are needed!
