### ISSUE TITLE
Discuss how to comunicate errors in fabsim commands to the user

### ISSUE THREAD

**Issue by velocirobbie** [djgroen/FabSim3#45]
How should we handle invalid/missing command line arguments, It would be useful to give the user some information on the arguments commands require. We should have a standardised way to do this. 

For the minute in FabMD.lammps_ensemble I have the lines
`if 'input_name_in_config' not in ensemble_args:
        raise RuntimeError('Must declare input_name_in_config: the generic name which sweep directory files will be changed to')`
We may not want the user to see the entire stack trace however.
Any other suggestions welcome

**Comment by djgroen** [comment]
This has been addressed with the new `fabsim` command  in the M12 release.
