### ISSUE TITLE
FabSim / VECMAtk logo

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#55]
Guys... I think it is time we think of designing one. Suggestions are welcome for logos of either type (I think we should have both ;)).

**Comment by dww100** [comment]
Could this issue be closed now?

**Comment by djgroen** [comment]
Yes, I think WP6 stylishly obliterated this task :D.

**Comment by djgroen** [comment]
Although.... we still need a FabSim logo :).

**Comment by djgroen** [comment]
We stick with the ones we have now :).
