### ISSUE TITLE
Password logged in FabSim environment variables dictionnary

### ISSUE THREAD

**Issue by mvassaux** [djgroen/FabSim3#56]
When executing a fab command, i.e `fab eagle lammps_ensemble:lammps_ensemble_execution,input_name_in_config="in.lammps"`, if the user is asked its password and enters it, the password is logged in an entry of the `env` fabric dictionnary called `passwords`. 

The entry is such as: `passwords : {login1 : password1, login2 : password2, ...}`

**Comment by djgroen** [comment]
Test is here: https://github.com/djgroen/FabSim3/blob/master/tests/test_fabsim.py
