### ISSUE TITLE
Definition of UQPs, Patterns and Primitives

### ISSUE THREAD

**Issue by dww100** [djgroen/FabSim3#69]
I'll outline my case as the start of a discussion on naming of components in VECMA.

Basically the P in UQP being primitive is misleading. In the proposal we set out UQP as algorithms applied to say cyclic or acyclic applications (amongst other things). This is clearly not a basic element, assuming the analogy is to primitive datatypes, but a complete workflow. The term primitive in the sense of basic building block is well established outside our clique of developers.

Replacing the term primitive with pattern allows allows us to retain the term UQP and associated definitions in the proposal. But the analogy is now with execution or design patterns. I don't think the analogy with ComPat concepts is bad, and that with design patterns is actively good.

The reason for wanting to do this is to allow us to use the term primitives for more basic elements. We have discussed at the UQP meeting the following ideas:
Sampling algorithms/approaches
Data structures/file formats to hold large vectors of correlated variables and/or their distributions
Aggregation functions
Analysis  algorithms/approaches
File formats and data structures for:
 -  problem definition
 -  run information

**Comment by djgroen** [comment]
I think we converged on the terminology at least in this discussion, but we need to share this with the wider consortium.

- [ ] @dww100 would you perhaps be willing to communicate this?

**Comment by djgroen** [comment]
I think we have reached agreement on this for the time being.
