### ISSUE TITLE
Some thoughts on getting job information

### ISSUE THREAD

**Issue by dww100** [djgroen/FabSim3#70]
I think one real benefit users might be able to get from a tool like FabSim is seeing job infor for multiple machines. There appear to be two solutions:

1. The most like FabSim is the regex schemes from SSH output used in things like [Longbow](https://github.com/HECBioSim/Longbow)
2. The [DRMAA](https://en.wikipedia.org/wiki/DRMAA) API 

I had though the latter would be a massive faff but looking at http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/drmaa.html
It could be quite easy to get jobids to query latter at least. This seems to work for https://github.com/pygridtools/gridmap and related tools.

**Comment by orbitfold** [comment]
I could look in to parsing ssh output since I've done a lot of that for my queue wait time prediction.

**Comment by djgroen** [comment]
@orbitfold Oh, that would be great. Thank you for picking this up!
