### ISSUE TITLE
Getting fabsim release into a docker image

### ISSUE THREAD

**Issue by olivhoenen** [djgroen/FabSim3#71]
For different use cases like training or dissemination events, it will be very intersting to get fabsim (as other vecmatk software) available from a docker type image, to allow quick testing, as discussed at the end of the project wide meeting in Garching.

**Comment by djgroen** [comment]
Initially I though the contents of .travis.yml could be used to convert to a Docker image, but that does not seem to be so straightforward. Does anyone here have experience with building Docker images?

What we need to do is given here:
https://github.com/djgroen/FabSim3/blob/master/.travis.yml

**Comment by PaulKarlshoeferBULL** [comment]
Unfortunately, I haven't used docker so far.

**Comment by orbitfold** [comment]
Why isn't using .travis.yml not straightforward? Technically though, you need to look at the contents of requirements.txt as well.

**Comment by arabnejad** [comment]
I just add the docker support for fabsim3, you can download by 
`docker pull vecmafabsim3/fabsimdocker`
and login into the docker by:
`docker run -it vecmafabsim3/fabsimdocker`

**Comment by djgroen** [comment]
@arabnejad Excellent! @olivhoenen would you, or someone else at IPP, care to give the Docker image a try in due time?
