### ISSUE TITLE
Enable "fab qcg dummy:dummy_test"

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#75]

**Comment by arabnejad** [comment]
an installation script for qcg-client on Ubuntu OS is added.
@djgroen could you please check it on your local machine and Let me know if you have any problem with that

**Comment by arabnejad** [comment]
based on the feedback from Diana @cspgdds  , `fab qcg` functionality works fine, her suggestion was to update the description on how to set machine configuration to be more clear, so, I am closing this issue and will update the documentation (`/doc/FabSim+QCG.md`)
