### ISSUE TITLE
Enable "fab <machine> dummy_ensemble:dummy_test,pilot_mode=True"

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#76]
This is a prototype syntax to run an ensemble of dummy jobs on a single remote machine using QCG-PilotJob. 

The goal of this task is to enable this functionality, so that users can easily test the PilotJob functionality from FabSim.

**Comment by djgroen** [comment]
Note: the final syntax may be different of course.

**Comment by arabnejad** [comment]
PilotJob functionality is added to FabSim3, please have look to `FabSim_PilotJob` branch
to submit a job, use `PilotJob=true` in your fab command
example : 
`fab qcg flee_ensemble:ssudan_ccamp,simulation_period=10,PilotJob=true`

**Comment by arabnejad** [comment]
NOW, PJ for both SLURM and QCG machine works
here are the step to do that : 

1. install QCG-PilotJob manager by 
> for QCG machine : `fab qcg install_app:QCG-PilotJob,virtual_env=True`
> For SLURM machine : `fab eagle install_app:QCG-PilotJob,virtual_env=True`
> **NOTE** : the installation path (`virtual_env_path`) is set on `machines.yml` as one of parameters for the target remote machine

2. run PilotJob by :
> for QCG machine : `fab qcg flee_ensemble:ssudan_ccamp,simulation_period=10,PilotJob=true`
> for SLURM machine : `fab eagle flee_ensemble:ssudan_ccamp,simulation_period=10,PilotJob=true`

**Comment by djgroen** [comment]
Euhmm... looks generally good, but ssudan_ccamp doesn't have a SWEEP dir in the repository? 

It does work with the `mali` config however.

**Comment by djgroen** [comment]
Most importantly, `fabsim qcg flee_ensemble:mali,N=20,simulation_period=50,PilotJob=true` appears to work correctly...

**Comment by djgroen** [comment]
So I will close this now, but we do need to test the Flee tutorial as a whole tomorrow.
