### ISSUE TITLE
 Add machine definitions (and template if applicable) for Genji to default machines.yml file. 

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#92]
Nicolas, could you work on this one?

**Comment by NicolasMonnier** [comment]
I think can add it (I just need to check if i'm allowed to). 
But keep in mind that Genji isn't open to external user (or only for specific collab)

**Comment by arabnejad** [comment]
Ok, just ask derek for the github permission
It can be easily fixed, right now, I am on way to airport, I will fix it as soon as I can :)

**Comment by djgroen** [comment]
@NicolasMonnier  I am aware of that, but nevertheless the definition is useful for those collaborators, and can also serve as a template for other, future machine integrations :).

**Comment by arabnejad** [comment]
thanks to @NicolasMonnier , `Genji` machine specification is added to [machines.yml](https://github.com/djgroen/FabSim3/blob/f75d95b31edb9ed25ad6a722cd49bd5aa582fc27/deploy/machines.yml#L383)
