### ISSUE TITLE
 Establish mechanisms to automate the installation of PJM on remote machines.

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#94]

**Comment by NicolasMonnier** [comment]
I did a first draft of the functionnality. 
If someone want to test it, you can find it in the `fabsim_bull_dev` branch.

How to use it :
`fab <remote_machine> install_app:name=QCG-PilotJob,external_connexion=yes`
`name=<name>` --> Application name
`external_connexion=<yes or no>` --> remote machine has internet access or not

For now, the default installation is `--user`
Moreover if you set external_connexion=no , You have to add : 
`app_repository: "<Path/where/you/want/to/save/the/dependencies/archive>"`
to your machine.yml or machine_user.yml

Let me know if you have any comments

**Comment by djgroen** [comment]
@arabnejad You have tested this, right? If so, feel free to close this issue.

**Comment by arabnejad** [comment]
the installation part is tested
