### ISSUE TITLE
Travis-CI build --- PEP8 Error

### ISSUE THREAD

**Issue by arabnejad** [djgroen/FabSim3#98]
Hi all

during past 6 months, and based on my observation, around 30% (or maybe higher) of `pep8` checks by Travis failed because of PEP8 check errors, my suggestion is to use a simple auto-formatting before pushing the code into GitHub repo
we can use (with aggressive level 1)::
`autopep8 --in-place --aggressive --max-line-length=79 <file_input>`
However, `autopep8` automates 98% or even 80% of the work and fails to fixed long comment line
so, we can test it on the local machine to be sure there will not be any `pep8` error 
`pycodestyle <file_input>`
and fix those remaining error manually (`pep8` has been renamed to `pycodestyle`)

I think we don't need to fixed all `.py` codes right now, but we can follow the same process on all new files

what do you think @djgroen  ?

**Comment by djgroen** [comment]
Sounds good, but do the others agree with the options set?

**Comment by djgroen** [comment]
Others are very silent.

So I'll add this as a recommendation to the Wiki.
